# Changes here will be overwritten by Copier
_commit: v3.3.0
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: stkr22@github.com
author_full_name: stkr22
codeowner_username: '@stkr22'
copyright_license: GPL-3.0
github_repository_name: private-assistant-commons-py
github_username: stkr22
project_description: Common utilities and base functionalities for all skills in the
    Private Assistant ecosystem.
project_name: Private Assistant Commons
publish_to_pypi: true
python_package_distribution_name: private-assistant-commons
python_package_import_name: private_assistant_commons
python_package_version: 3.6.0
use_containers: false
