# Changes here will be overwritten by Copier
_commit: 1.3.3
_src_path: https://github.com/stkr22/copier-python-project.git
author_email: stkr22@github.com
author_full_name: stkr22
codeowner_username: '@stkr22'
copyright_license: GNU General Public License v3.0
project_description: Common utilities and base functionalities for all skills in the
    Private Assistant ecosystem.
project_name: Private Assistant Commons
publish_to_pypi: true
python_package_distribution_name: private-assistant-commons
python_package_import_name: private_assistant_commons
use_containers: false
