FROM mcr.microsoft.com/devcontainers/base@sha256:ce2e9e611939e611b737362c045bb6d3449bb3efb84898525d724aace1737b90
COPY --from=ghcr.io/astral-sh/uv:0.7.21@sha256:a64333b61f96312df88eafce95121b017cbff72033ab2dbc6398edb4f24a75dd /uv /uvx /bin/
ENV VIRTUAL_ENV=/workspaces/.venv
ENV UV_PROJECT_ENVIRONMENT=/workspaces/.venv
RUN mkdir -p /workspaces && \
    chown -R vscode:vscode /workspaces
USER vscode
